2018-07-01 21:32:41,307 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    EventForm.val_date(form,form.end_time.data)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
2018-07-01 21:33:37,326 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    EventForm.val_date(form,form.end_time.data)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
2018-07-01 21:33:37,326 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    EventForm.val_date(form,form.end_time.data)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
2018-07-01 21:34:14,146 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    EventForm.val_date(form,form.end_time.data)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
2018-07-01 21:34:14,146 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    EventForm.val_date(form,form.end_time.data)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
2018-07-01 21:35:37,154 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    db.session.add(event)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
2018-07-01 21:35:37,154 ERROR: Exception on /makeevent [POST] [in G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\My Drive\Python\FlaskGuide\virtual\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\My Drive\Python\FlaskGuide\app\main\routes.py", line 147, in event
    db.session.add(event)
  File "G:\My Drive\Python\FlaskGuide\app\main\forms.py", line 44, in val_date
    raise ValidationError('fuck je moeder')
wtforms.validators.ValidationError: fuck je moeder
